---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnet-api
  template:
    metadata:
      labels:
        app: aspnet-api
    spec:
      containers:
      - env:
          - name: ConnectionStrings__pgsql
            value: 'Host=localhost;Database=AstroflixDB;Username=postgres;Password=postgres;'
        name: aspnet-api
        image: fredbelotte/api2020
        ports:
          - containerPort: 80
            name: aspnet-api-http   
      
      - env:
          - name: POSTGRES_PASSWORD
            value: postgres
        image: postgres
        imagePullPolicy: Always
        name: postgres
        ports:
          - containerPort: 5432
            name: postgres-tcp
