jobs:
  build_angular:
    defaults:
      run:
        working-directory: angular/ng10/
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm run lint

  build_aspnet_api:
    defaults:
      run:
        working-directory: aspnet_api/
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: dotnet restore
      - run: dotnet build --no-restore

  build_aspnet_mvc:
    defaults:
      run:
        working-directory: aspnet_mvc/
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: dotnet restore
      - run: dotnet build --no-restore

name: pipeline

on: push
